- name: Update Polkadot on EC2 instances
  hosts: aws_cluster
  become: true
  tasks:
    - name: Pull Polkadot Docker image
      community.docker.docker_image:
        name: parity/polkadot
        tag: v1.2.0  
        source: pull

    - name: Stop existing Polkadot container
      community.docker.docker_container:
        name: polkadot
        state: stopped
        force_kill: yes 

    - name: Remove existing Polkadot container
      community.docker.docker_container:
        name: polkadot
        state: absent 

    - name: Run Polkadot container with new version
      community.docker.docker_container:
        name: polkadot
        image: parity/polkadot:v1.2.0 
        state: started
        restart_policy: always
        ports:
          - "30333:30333"   # P2P port
          - "9933:9933"     # RPC port
          - "9944:9944"     # WebSocket port
          - "9615:9615"     # Prometheus port
